FROM alpine

RUN apk update
RUN apk add openrc
RUN apk add iproute2 dhcp pciutils dmidecode curl bridge-utils

COPY init1 /init
# Copy from kernel build container /lib/modules/
COPY 6.12.1 /lib/modules/6.12.1
RUN chmod +x /init
RUN echo 'root:rootmydocker' | chpasswd
